backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "images/uploads"
collections:
  - name: "employees"
    label: "Employees"
    folder: "employees"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Birth Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "Group"
        name: "group"
        widget: "relation"
        collection: "groups"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
      - label: "tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        multiple: true
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]

  - name: "groups"
    label: "Groups"
    folder: "groups"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Group", name: "title", widget: "string"}

  - name: "Tags"
    label: "tags"
    folder: "tags"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tag", name: "title", widget: "string"}
